chore : Copy previous work
f-lab-edu/pfairplay pull request #1
Opened 2024-03-06 12:49 UTC by dgryoo

- Spring, DB, Lombok, QueryDsl 의존성 추가
- Exception 관리를 위한 Handler, Response 클래스들 추가
- 날짜 다루는 Util 추가
- Member, Team, MemberTeam 관련 Entity, Repository, Service, Controller 추가 (  수정 필요 )

2024-03-06 14:55 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFExceptionHandler.java
> +@Order(1)
익셉션 핸들링 클래스가 두 개인데, 핸들러를 두개로 분류한 기준이 따로 있는 것인가요? 그리고 이렇게 분류하는 것이 꼭 필요한 것이었나요?

2024-03-06 14:57 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFError.java
> +@Setter()
nit:

```suggestion
@Setter
```

2024-03-06 14:59 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFResponse.java
> +public class PFResponse {
이 클래스는 에러를 위해서만 존재하는 클래스인가요? 그렇다면, 이름을 좀 더 적절하게 바꾸는 것이 좋을 것 같습니다.

2024-03-06 15:01 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFExceptionHandler.java
> +        pfErrors.add(PFError.fromPFErrorEnum(e.getPFErrorEnum()));
```suggestion
        List<PFError> pfErrors = new ArrayList<>();
        pfErrors.add(PFError.fromPFErrorEnum(e.getPFErrorEnum()));
```

이 코드는 안 쓰는 코드인거죠?

2024-03-06 15:02 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFException.java
> +    private final HttpStatus httpStatus;
구조적으로 보면, `PFException`을 하나만 두고, `HttpStatus`를 여러개로 두는 것보다는 `PFException`을 상속받는 세부 클래스를 만들어서 각각 다른 `HttpStatus`를 적용하는 것이 더 좋은 방법일 것 같습니다.

2024-03-06 15:04 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/GlobalExceptionHandler.java
> +        System.out.println("Path : " + httpServletRequest.getRequestURI());
nit:

```suggestion
        logger.debug("Method : %s", httpServletRequest.getMethod());
        logger.debug("Path : %s", httpServletRequest.getRequestURI());
```

2024-03-06 15:05 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/GlobalExceptionHandler.java
> +        e.printStackTrace();
```suggestion
```

2024-03-06 15:07 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFError.java
> +    public static PFError fromPFErrorEnum(PFErrorEnum pfErrorEnum) {
위에서 코드를 사용하는 패턴을 보면, 이 메소드를 여기보다는 PFErrorEnum밑에 두고, toPFError를 만들어 주는게 더 편하게 사용할 수 있지 않을까 싶네요.

2024-03-06 15:08 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFResponse.java
> +@Getter
이 부분에서 `@Getter`는 꼭 필요한 것인가요? 꼭 필요하다면, 어떤 이유인지 설명해 주실 수 있을까요?

2024-03-06 15:09 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFErrorEnum.java
> +
```suggestion
```

2024-03-06 15:15 UTC, f-lab-lyan requested changes
일단 common/exception 부분에 대해서 리뷰를 남겼습니다. 그리고 이 PR을 머지하기 전에 gradle multi-module구조로 변경하고 머지하는 것이 좋아보입니다. 이 부분만 추가로 작업해 볼까요?

2024-03-07 01:43 UTC, dgryoo commented on src/main/java/com/pfairplay/api/common/exception/PFExceptionHandler.java
> +@Order(1)
프로젝트에서 커스텀으로 만든 에러, Spring에서 제공하는 에러 ( ex: org.springframework.web.bind.MethodArgumentNotValidException)들을 따로 관리하려고 분류 했습니다. 같이 있어도 상관이 없긴 한데 두개가 하는 역할이 조금 다르다고 생각했습니다.

2024-03-07 01:47 UTC, dgryoo commented on src/main/java/com/pfairplay/api/common/exception/PFResponse.java
> +public class PFResponse {
PF 라는게 프로젝트 이름이였는데 Custom으로 전부 바꿨습니다. Error가 발생했을때 Response를 위한 클래스라 CustomErrorResponse로 이름을 바꿨습니다.

2024-03-07 01:51 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFExceptionHandler.java
> +@Order(1)
일반적으로 같은 역할을 하는 클래스가 두 개 이상 존재하면, 나중에 비니지스 로직이나 일반적인 코드를 넣을 때, 어디에 넣을지 고민해야하는 상황에 빠지게 되죠. 그래서 동일한 기능을 하는 클래스라면, 한군데 넣고, 관리하는 것이 더 좋은 것 같습니다. 물론 프로젝트 규모가 아주 커져서, 그 기준이 비교적 명확한 상황이 되면, 나눌 수도 있을 것 같지만, 지금은 그정도 규모는 아니어서, 일단 하나로 작업하다가 나중에 정말로 필요해졌을 때, 나누는 것이 좋을 것 같습니다.

2024-03-07 01:52 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFResponse.java
> +public class PFResponse {
바꿀꺼라는 말씀이신거죠? 커밋이 추가로 올라온 것 같지는 않네요.

2024-03-07 01:53 UTC, dgryoo commented on src/main/java/com/pfairplay/api/common/exception/PFException.java
> +    private final HttpStatus httpStatus;
SOURCE_NOT_FOUND, BAD_REQUEST_ERROR, INTERNAL_SERVER_ERROR, DUPLICATE_ENTRY
요렇게가 지금 우선 사용하고 있는 것들인데 

각각 해당 클래스를 상속받아서 CustomSourceNotFoundException extends CustomException {}
이렇게 말씀이실까요?

2024-03-07 01:55 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFException.java
> +    private final HttpStatus httpStatus;
네, 맞습니다. 실제로 비니지스 로직에서 익셉션을 던진다고 가정해 보면, 위와 같이 코드를 바꾸면, 그냥 
```
throw new CustomSourceNotFoundException("message");
```
라고만 하면 될테니, 사용하는 입장에서는 좀 더 편하게 사용할 수 있겠죠.

2024-03-07 02:02 UTC, dgryoo commented on src/main/java/com/pfairplay/api/common/exception/PFResponse.java
> +@Getter
class GlobalExceptionHandler

```
@ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<CustomErrorResponse> handleException(MethodArgumentNotValidException e) {

        CustomErrorResponse customErrorResponse =
                new CustomErrorResponse(
                        HttpStatus.BAD_REQUEST.value(),
                        CustomError.fromCustomErrorEnum(CustomErrorEnum.BAD_REQUEST_ERROR));

        e.getBindingResult().getFieldErrors().forEach(error -> {
            customErrorResponse.getError().getErrors().put(error.getField(), error.getDefaultMessage()); // 이부분에서 사용 중입니다.
        });

        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(customErrorResponse);
    }
```
    
    해당 메소드는 DTO Validation 할때 아래와 같은 response를 기대하고 만들었습니다.
```
    {
    "statusCode": 400,
    "error": {
        "title": "올바르지 않은 형식의 요청입니다.",
        "message": "요청을 확인해 주세요.",
        "errors": {
            "phoneNumber": "핸드폰 번호를 작성해 주세요.",
            "birthDate": "생년월일을 작성해 주세요."
        }
    }
}
```

2024-03-07 02:06 UTC, dgryoo commented
> 일단 common/exception 부분에 대해서 리뷰를 남겼습니다. 그리고 이 PR을 머지하기 전에 gradle multi-module구조로 변경하고 머지하는 것이 좋아보입니다. 이 부분만 추가로 작업해 볼까요?

멀티모듈 구조를 어떻게 가져가면 좋을지 잘 모르겠습니다. 처음에 시도할때는 아래처럼 만들려고 시도 했었습니다.
api-server( Controller, Service, Spring config)
batch-server( Batch Job, Spring config ) // 아직 만들계획 없음
database-core ( Entity, Repository, DB config )
common ( 기타 등등 공통으로 쓰는 것들)

2024-03-07 02:08 UTC, f-lab-lyan commented on src/main/java/com/pfairplay/api/common/exception/PFResponse.java
> +@Getter
아 이해했습니다. 일반적으로 객체를 받아서 넘기면되도록 작성하기때문에 필요없을 것 같은데, 좀 더 고민해보시면 좋을 것 같습니다.

2024-03-07 02:10 UTC, f-lab-lyan commented
>멀티모듈 구조를 어떻게 가져가면 좋을지 잘 모르겠습니다. 처음에 시도할때는 아래처럼 만들려고 시도 했었습니다.
api-server( Controller, Service, Spring config)
batch-server( Batch Job, Spring config ) // 아직 만들계획 없음
database-core ( Entity, Repository, DB config )
common ( 기타 등등 공통으로 쓰는 것들)

사실은 이걸 고민해보는게 제가 기대한 부분이었는데요. 일단은 지금은 다른 것이 다 필요없으니, api-server하나만 있으면 되지 않을까 싶네요. 지금 필요하지 않은걸 미리 만들어 두면, 코드의 복잡도만 증가할 뿐, 얻을 수 있는 이득이 거의 없다고 생각합니다.

2024-03-07 12:59 UTC, f-lab-lyan commented on src/main/resources/application.yml
> +    open-in-view: false
<img width="113" alt="image" src="https://github.com/f-lab-edu/pfairplay/assets/90605505/ddb1b4fc-07a0-49b7-b232-a5cb07c93e07">

이것의 정체는 뭘까요?

2024-03-14 11:12 UTC, merged