Docker 적용
f-lab-edu/pfairplay pull request #5
Opened 2024-03-20 09:44 UTC by dgryoo

- After : https://github.com/f-lab-edu/pfairplay/pull/4
- api-server는 8080, mysql은 3307 (로컬 mysql이 이미 3306 쓰고 있어서)로 띄우도록 하였습니다. 
- .env파일을 사용해서 dockerCompose에서 환경변수를 사용하도록 했습니다. env는 gitignore 처리 했습니다.
```
--  .env --
MYSQL_DATABASE=pfairplay
MYSQL_TCP_PORT=3307
MYSQL_URL=jdbc:mysql://mysql:${MYSQL_TCP_PORT}/${MYSQL_DATABASE}
MYSQL_USERNAME=root
MYSQL_PASSWORD=pwd
```

2024-03-20 09:58 UTC, f-lab-lyan requested changes
이 PR은 다른 코드 변경과는 관계가 없을 것 같으니, main에서 새로 따서 브랜치를 만들어 주실래요? 그러면 다른 변경사항 없이 docker관련된 변경 사항만 보일 것 같네요.

2024-03-20 09:59 UTC, f-lab-lyan commented on Dockerfile
> +COPY api-server/build/libs/api-server-1.0.0.jar .
이렇게하면, 빌드가 다 된 상태에서만 docker를 돌릴 수 있는데, docker-compose에서 빌드까지 하던가, 아니면, API서버를 도커에 올리지 않거나 하는 두 가지 중 하나를 선택할 수 있을 것 같네요. 더 선호하시는 쪽으로 진행해 주시면 될 것 같습니다. :-)

2024-03-20 10:17 UTC, dgryoo commented
> 이 PR은 다른 코드 변경과는 관계가 없을 것 같으니, main에서 새로 따서 브랜치를 만들어 주실래요? 그러면 다른 변경사항 없이 docker관련된 변경 사항만 보일 것 같네요.

변경해두었습니다!

2024-03-20 10:20 UTC, dgryoo commented on Dockerfile
> +COPY api-server/build/libs/api-server-1.0.0.jar .
빌드까지 하는걸로 바꿔보겠습니다.

2024-03-21 11:16 UTC, f-lab-lyan commented on Dockerfile
> +COPY api-server/build/libs/api-server-1.0.0.jar .
https://docs.docker.com/build/building/multi-stage/

2024-04-22 11:07 UTC, merged